### ISSUE TITLE
v2019.1 meta tracking

### ISSUE THREAD

**Issue by thefallentree** [fluffos/fluffos#448]
V2019.1.X will be a major feature release, with build target upgrade.
V2019.2.X will be a minor feature release, without build target upgrade.

# System Support

## Language
- [X] std=c++17 features, but libstdc++6 (without builtin filesystem library)

# OS
- [x] ubuntu 18.04 (default) 
- [X] ubuntu 16.04 (with GCC/Clang upgrade)
- [X] OSx 10.15
- [X] Windows + WSL ubuntu 18.04
- [X] Windows + MSYS2/MINGW64

# Build System

- [X] CMake 3.10 + (default on ubuntu 18.04)
- [X] have 4 mode: 
   - [x] release (native) 
   - [X] release (generic) 
   - [X] dev 
   - [X] dev with CHECK_MEMORY & DEBUGMALLOC

# Functionality
- [X] LPC string is UTF8 native
     - [X] LPC lexer validate source code is UTF8
     - [X] testsuite with utf8 test cases.
     - [X] strlen, [] , and [..] range operator support UTF8
     - [X] sprintf utf8 alignment support
     - [X] EFUN for set output/input encoding for each user
- [X] Native websocket support (libwebsocket)
- [X] JSON sefun for serialize/de-serialize MUD types to JSON

# TODO
## System
- [ ] centos 8.0 (maybe with GCC/Clang upgrade)
- [ ] Windows + VS2017 (or maybe Mingw64 for now)
## EFUNS
- [ ] #449 EFUN to print all efuns.
## Tooling / Ecosystem
- [ ] standalone compiler to output AST / byte code / dissembler
- [ ] LPC code formatter based on astyle
- [ ] Electron based Shell + Client
- [ ] support .lpc extension everywhere.

**Comment by thefallentree** [comment]
Updated base on feature poll

**Comment by thefallentree** [comment]
#527 #544  #550
